import { Navbar } from '@/components/navbar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <div className="grid grid-cols-6 flex-grow">
          <div className="col-span-1">
            {/* Sol tarafta yer alan içerik */}
          </div>
          <div className="text-center col-span-3">
          {/* Orta kısımda yer alan içerik */}
          {children}
        </div>
          <div className="col-span-2">
            {/* Sağ tarafta yer alan içerik */}
          </div>
        </div>
        
      </body>
    </html>
  );
}
